
SRCS:= \
	h8300s/cybiko/locore \
	h8300s/cybiko/machdep.c \
	h8300s/arch/cpufunc.S \
	h8300s/arch/cpu.c \
	h8300s/arch/context.c \
	h8300s/cybiko/interrupt.c \
	h8300s/arch/trap.c \
	h8300s/cybiko/clock.c
